### PR TITLE
[Feature] #61 Fetch Editor Data, Editor Image

### LINKED ISSUE #61: [Feature] Fetch Editor Data, Editor Image
# 유저는 에디터 콘텐츠를 구경할 수 있다
- 에디터 콘텐츠의 Entity data와 image를 ViewModel으로 fetch 해온다.

## 🤔 Completion conditions

- [ ] In ViewModel can fetch data & image

## 👀 Related issues

- Related issue1 #39

### PR DESCRIPTION
**Pull request by Gobans**
# Issue Number
🔒 Close #61 

## Changes

- Changed files
campair/campair.xcodeproj/project.pbxproj
"campair/campair/Application/Images/\352\262\275\353\237\211_\354\262\264\354\226\264.png"
"campair/campair/Application/Images/\354\260\250\353\241\234_\353\226\240\353\202\230\353\212\224_\355\224\274\355\201\254\353\213\211.png"
Entity{
campair/campair/Entity/Editor/ContentEquipment.swift
campair/campair/Entity/Editor/Main/EditorMainCollection.swift
campair/campair/Entity/Editor/Main/EditorMainContent.swift
campair/campair/Entity/EditorMainCollectionData.json
}
campair/campair/Model/EditorRepository.swift
campair/campair/UseCase/EditorUseCase.swift
campair/campair/View/ContentView.swift
campair/campair/View/Editor/Main/EditorCardView.swift
campair/campair/View/Editor/Main/EditorMainView.swift

## New features

- Make fetch data, image function (using url)
- Revise Entity for fetch images

## Review points

- EditorMainViewModel
- EditorRepository
- Entities

## References

- Smile's repository

## Checklist

- [x] Is the branch you are merging on correct?
- [x] Do you comply with coding conventions?
- [x] Are there any changes not related to PR?
- [x] Has my code been self-reviewed?

### CODE REVIEW

**Review by rriver2 — APPROVED** [review]
고생했어요..! 고반, I will study with your code ~

**Review by sustainable-git — APPROVED** [review]
GGOODD!

**Comment by jinwp** [comment]
Great job, Goban!

**Review by mijinc — APPROVED** [review]
Thank you for your hard work!!

**Pull request merged**
