### PR TITLE
[Project] #3 : Add gitignore

### LINKED ISSUE #3: [Project] Gitignore

### PR DESCRIPTION
**Pull request by sustainable-git**
# Issue Number
🔒 Close #3

## Changes

- Changed files
    - .gitignore

## New features

- New gitignore

## Checklist

- [x] Is the branch you are merging on correct?
- [x] Do you comply with coding conventions?
- [x] Are there any changes not related to PR?
- [x] Has my code been self-reviewed?

### CODE REVIEW

**Review by Gobans — APPROVED** [review]
LGTM

**Review by rriver2 — APPROVED** [review]
good !

**Review by Gobans — APPROVED** [review]

**Review by vveryberry — APPROVED** [review]
nice

**Review by mijinc — APPROVED** [review]
Awesome!

**Pull request merged**
